exports.seed = function (knex, Promise) {
  return knex('recipes').del()
    .then(function () {
      return Promise.all([
        knex('recipes').insert({id:99901, category_id: 2201, recipe_name: 'Chocolate Layer Cake', chef_name:'Ina Garten aka The Barefoot Contessa', recipe_image_url: 'http://food.fnr.sndimg.com/content/dam/images/food/fullset/2007/3/22/0/ig0807_cake.jpg.rend.hgtvcom.616.462.jpeg', recipe_ingredients: '1 3/4 cups flour, plus more for dusting cake pans, 2 cups sugar, 3/4 cups cocoa powder, 2 teaspoons baking soda, 1 teaspoon baking powder, 1 teaspoon kosher salt, 1/2 cup oil, 2 large eggs, 1 teaspoon vanilla extract, 1 cup hot, strong coffee', recipe_text:
        'Directions: Preheat oven to 350°F. Butter two 8-in cake pans and dust with flour. Combine all dry ingredients in the bowl of a stand mixer and mix until combined. In a small bowl, combine buttermilk, oil, eggs, and vanilla. Pour buttermilk mixture into dry ingredients and beat just until smooth. Add coffee and mix just until incorporated. Divide batter, which will be incredibly runny, evenly between the two pans. Bake for 35 to 40 minutes until a toothpick stuck in the center of each cake comes out clean. Remove from oven and allow to cool in the pans for 10-15 minutes before turning out onto a wire rack to cool completely. Frost cakes as desired.', recipe_comments: "This is Ina's famous chocolate cake, loved by home-bakers the world over. It's sure to be a family-favorite."}),

        knex('recipes').insert({id:99902, category_id: 2202, recipe_name: 'Gooseberry and Strawberry Tart', chef_name:'Hugh Fearnley-Whittingstall', recipe_image_url: 'https://i.guim.co.uk/img/static/sys-images/Guardian/About/General/2012/6/21/1340285168356/Hugh-Fearnley-Whittingsta-008.jpg?w=620&q=55&auto=format&usm=12&fit=max&s=2af9067714472e4c764195da88ba5427', recipe_ingredients: 'For the filling, 200g gooseberries, topped and tailed, 200g strawberries, hulled and halved or quartered, 75g caster sugar, plus a little extra to finish, Finely grated zest of 1 lemon, 3 tbsp ground almonds, 1 egg white, lightly beaten, For the sweet shortcrust pastry, 200g plain flour, 1 heaped tbsp icing sugar, Pinch of salt,120g cold, unsalted butter, cut into cubes, 1 egg yolk, About 50ml cold milk (or water)', recipe_text: 'For the pastry, put the flour, sugar and salt in a food processor, blitz briefly to combine, then add the butter and blitz until it resembles breadcrumbs. To make it by hand, rub in the butter with your fingertips. Add the egg yolk and enough milk or water to bring it together into large clumps. Tip on to a lightly floured surface and knead lightly into a ball. Wrap in clingfilm and chill for 30 minutes. Combine the berries, sugar and lemon zest, and set aside to macerate for 30 minutes. Heat the oven to 200C/400F. Line a large baking tray with baking parchment or nonstick liner – use a tray with a slight edge, as the tart may leak juice while baking. On a floured surface, roll out the pastry to a rough circle, 2-3mm thick and about 35cm in diameter, and transfer to the baking tray. Sprinkle the ground almonds evenly over the top without going right to the edges. Spoon the macerated fruit, and any juices, over the pastry, leaving a 3-4cm border. Fold the border inwards over the fruit, brush the pastry edges with the egg white and sprinkle with more caster sugar. Bake for 30 minutes, or until the pastry is a deep gold. Serve warm, with cream or ice-cream.'
        , recipe_comments:'This The River Cottage OG himself.'}),

        knex('recipes').insert({id:99903, category_id: 2203, recipe_name: 'Salted Chocolate Chip Cookies', chef_name:'Christina Tosi', recipe_image_url: 'http://www.foodiecrush.com/wp-content/uploads/2015/05/Milk-Bar-Salted-Chocolate-Chip-Cookies-foodiecrush.com-36.jpg', recipe_ingredients: '225g unsalted butter, melted and just warm to the touch 3/4 cup packed light brown sugar, 1/2 cup granulated sugar, 1 egg, 2 teaspoons vanilla extract, 1 3/4 cups all-purpose flour, 2 tablespoons nonfat milk powder, 1 1/4 teaspoons kosher salt, 1/2 teaspoon baking powder, 1/4 teaspoon baking soda, 12 ounces semisweet chocolate chips or chocolate chunks 1/4 cup flaked salt', recipe_text: 'Preheat the oven to 375 degrees F. With a wooden spoon, mix the sugars together in a large bowl and add the melted butter. Stir vigorously for about a minute or more. Mix the egg and vanilla in the measuring cup you used for the sugar and add to the mixture. Stir until the mix gathers a glossy sheen, about one more minute. Mix in the flour, milk powder, salt, baking powder, and baking soda until just combined. Stir in the chocolate chips and mix until evenly distributed. Lightly form dough into balls about the size of a golf ball, and place on a baking tray lined with parchment paper about 2 to 3 inches apart. Bake for 9-11 minutes or until golden brown around the edges but still soft in the middle. The cookies will fall as they cool. Transfer to a cooling rack to cool completely.'
        , recipe_comments:''}),

        knex('recipes').insert({id:99904, category_id: 2204, recipe_name: 'Old Fashioned Bread Pudding', chef_name:'Betty Crocker', recipe_image_url: '', recipe_ingredients: '2 cups milk, 1/4 cup butter, 2 eggs, slightly beaten, 1/2 cup sugar, 1 teaspoon ground cinnamon or nutmeg, 1/4 teaspoon salt, 6 cups soft bread cubes (about 6 slices bread), 1/2 cup raisins, Whipping (heavy) cream, if desired', recipe_text: 'Heat oven to 350ºF. In 2-quart saucepan, heat milk and butter over medium heat until butter is melted and milk is hot. In large bowl, mix eggs, sugar, cinnamon and salt. Stir in bread cubes and raisins. Stir in milk mixture. Pour into ungreased deep round pan. Bake uncovered 40 to 45 minutes or until knife inserted 1 inch from edge comes out clean. Serve warm with whipping cream.', recipe_comments:''}),

        knex('recipes').insert({id:99905, category_id: 2205, recipe_name: 'Pumpkin Seed Brittle', chef_name:'Alison Roman', recipe_image_url: 'http://assets.bonappetit.com/photos/57addc3c1b334044149756e8/16:9/w_1028,c_limit/pumpkin-seed-brittle.jpg', recipe_ingredients: 'Nonstick vegetable oil spray, 1 cup sugar, 1/2 cup light corn syrup, 1 cup raw shelled pumpkin seeds (pepitas), 2 tablespoons unsalted butter, 1 teaspoon kosher salt, 3/4teaspoon baking soda, 1/8 teaspoon ground cinnamon, 1/4 teaspoon flaky sea salt', recipe_text: 'Spray a parchment-lined baking sheet with nonstick spray and set aside. Bring sugar, corn syrup, and 3 Tbsp. water to a boil in a medium saucepan over medium heat, stirring to dissolve sugar. Fit saucepan with thermometer and cook until thermometer registers 290°, 3-4 minutes. Stir in pumpkin seeds, butter, and kosher salt and cook, stirring often, until pale brown and thermometer registers 305°, 3–4 minutes. Stir in baking soda and cinnamon (mixture will bubble vigorously), then immediately pour caramel onto prepared sheet. Using a heatproof spatula, quickly spread out and sprinkle with sea salt; let cool. Break brittle into pieces.'
        , recipe_comments:''}),

        knex('recipes').insert({id:99906, category_id: 2206, recipe_name: 'Challah', chef_name:'Yotam Ottolenghi', recipe_image_url: 'https://i.guim.co.uk/img/media/f9c0eb7303e8cf2823b0a949f8feddbfffc5986c/31_1759_2963_1778/master/2963.jpg?w=620&q=55&auto=format&usm=12&fit=max&s=9162c7b6eb9ac785fa2a6e5713f45c99', recipe_ingredients: '2 1/2 tsp fast-action yeast, 200ml lukewarm water, 90g caster sugar, 580g strong bread flour, 1 tbsp flaked sea salt , 3 eggs, beaten, 60ml sunflower oil, plus 1 tsp extra to grease a bowl, 60g unsalted butter, cubed and at room temperature', recipe_text: 'Mix the yeast and water in a small bowl with half a teaspoon of sugar, then set aside for 15 minutes, until it starts to froth. Put the rest of the sugar in the bowl of an electric mixer with the dough hook in place. Add the flour and salt, mix slowly to combine, then add the yeast mix, two of the beaten eggs, the oil and butter, and mix slowly until it comes together into a dough. Raise the speed to medium-high and beat for eight minutes, until smooth, soft and elastic. Transfer to a large bowl brushed with oil, cover with a clean tea towel and leave somewhere warm for about two hours, until doubled in size. Divide the dough into three equal pieces, then roll and pull each piece into a 45cm-long x 4-5cm-thick sausage. Position the three sausages side by side on a large sheet of greaseproof paper, and press together the top three ends, to join, then braid the three sausages into a plait; to finish, press the bottom three ends together, as with the tops, to join and seal. Tuck both ends under the plait to neaten the look and stop the whole thing unravelling, then cover again with the tea towel and leave to rise for 75 minutes. Meanwhile, heat the oven to 180C/350F/gas mark 4, and heat up a 30cm x 40cm baking tray. Brush the plait all over with the third beaten egg, making sure you get it into all the crevices, then lift the bread, still on its paper, on to the hot baking tray. Bake for 30 minutes, until the top is a deep golden-brown and the underneath of the bread is also dark and sounds hollow when you tap it. Set aside to cool before serving'
        , recipe_comments:'Challah back!'}),

        knex('recipes').insert({id:99907, category_id: 2207, recipe_name: '', chef_name:'', recipe_image_url: '', recipe_ingredients: '', recipe_text: '', recipe_comments:''}),

        knex('recipes').insert({id:99908, category_id: 2208, recipe_name: '', chef_name:'', recipe_image_url: '', recipe_ingredients: '', recipe_text: '', recipe_comments:''}),

        knex('recipes').insert({id:99909, category_id: 2209, recipe_name: '', chef_name:'', recipe_image_url: '', recipe_ingredients: '', recipe_text: '', recipe_comments:''}),

        knex('recipes').insert({id:99910, category_id: 2201, recipe_name: '', chef_name:'', recipe_image_url: '', recipe_ingredients: '', recipe_text: '', recipe_comments:''})
      ]);
    });
};
